.TH CPU 1 "2013 April 3" "cpu-0.0.4"
.SH NAME
cpu \- x-platform cpu infos
.SH SYNOPSIS
\fBcpu\fP [\fI--version\fP] [\fI--help\fP] [\fIcommand\fP]
.SH DESCRIPTION
.B cpu
is a shell script that abstracts away the differences between operating systems when retrieving cpu hardware info .
.SH AUTHORS
Jesse Tane
.br
jesse.tane@gmail.com
